# Generated by Django 3.2.4 on 2021-06-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectfee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='lastName',
            new_name='AnyOtherUni',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='firstName',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Aadhaar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='AnnualIncome',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='FirstName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='LastName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
