# Generated by Django 3.2.4 on 2021-06-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectfee', '0003_alter_applicationform_annualincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='City',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Elective1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Elective2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Elective3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Employment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='FatherName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='FullMarks1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='FullMarks2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='FullMarks3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='FullMarks4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='FullMarks5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='FullMarks6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Grade1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Grade2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Grade3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Grade4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Grade5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Grade6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='MarkObtain1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='MarkObtain2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='MarkObtain3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='MarkObtain4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='MarkObtain5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='MarkObtain6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Martial',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='MiddleName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Minority',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='MotherName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='PayingGuest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Preference1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Preference2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Preference3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='State',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='Transport',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
