# Generated by Django 3.2.4 on 2021-06-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectfee', '0005_auto_20210625_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='martial',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
