# Generated by Django 3.2.4 on 2021-06-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectfee', '0007_auto_20210625_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='aadhaar_img',
            field=models.ImageField(default=None, null=True, upload_to='uploads/aadhaar/'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='marksheet_img',
            field=models.ImageField(default=None, null=True, upload_to='uploads/marksheet/'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='profile_img',
            field=models.ImageField(default=None, null=True, upload_to='uploads/profile/'),
        ),
    ]
