# Generated by Django 3.2.4 on 2021-06-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectfee', '0008_auto_20210625_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='aadhaar_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='marksheet_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='profile_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
