# Generated by Django 3.2.4 on 2021-06-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectfee', '0009_auto_20210625_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='email_sent_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
