# Generated by Django 3.2.4 on 2021-06-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectfee', '0010_applicationform_email_sent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='annualIncome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
