# Generated by Django 3.2.4 on 2021-06-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectfee', '0012_auto_20210626_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='agreecollege',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='agreepay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='board12',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='pwd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
