# Generated by Django 3.2.4 on 2021-06-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectfee', '0013_auto_20210627_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='aadhaar',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
